### ISSUE TITLE
Cannot accept new request member without skill to a team 

### ISSUE THREAD

**Issue by AndrewPang321** [COMP3111-404-Not-Found/Team-Form#100]
- A team cannot accept a new request from a member if he/she doesn't have any skill.

**Comment by chautsunman** [comment]
- `$scope.joinEvent()` in the index page does not copy the user's skills to the member object of the event

**Comment by chautsunman** [comment]
- all users must have at least 1 skill
- all teams must have at least 1 preferred skill
