### ISSUE TITLE
Create an about page

### ISSUE THREAD

**Issue by stevenTCL** [COMP3111-404-Not-Found/Team-Form#28]
I will do the UI first.

**Comment by chautsunman** [comment]
- about the team form website
- about the development team
- about the development process

**Comment by chautsunman** [comment]
UI components:
- card/white-frame (Angular Material or Material Design Lite)
- navbar (Material Design Lite)

**Comment by stevenTCL** [comment]
Oh. Missed the msg. I will add the cards later.
While the three "about" are done.
